### ISSUE TITLE
some documentation or info please....

### ISSUE THREAD

**Issue by roboto-cloud** [andyceo/ansible-role-configurator#1]
Hi, I need sync from local to remote
I use this:

```
  rsyncdirs: 
    - src: /home/local/folder,
    - dest: /home/remote/folder
```
and get this issue:

```
fatal: [us18v-240]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'unicode object' has no attribute 'dest'\n\nThe error appears to have been in '/home/rbt/→/io/iac/ans/roles/sync-push/tasks/main.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# @see https://github.com/ansible/ansible/issues/23834\n- name: Synchronize whole directories with rsync\n  ^ here\n"}

```
someone can tell me who work with it?

thank in advance,

**Comment by roboto-cloud** [comment]
I was it work whit:

```
  rsyncdirs: {}

  fulldirs:
    item:
      src: /home/local/folder
      dest: /home/remote/folder
      archive: no

  directories:

```
